# Generated by Django 2.2.4 on 2020-03-28 14:25

from django.db import migrations

def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(name=flat.owner, phone=flat.owners_phonenumber, phone_pure=flat.owner_phone_pure)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(create_owners),
    ]
