# Generated by Django 2.2.4 on 2020-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20200330_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='user',
            new_name='customer',
        ),
    ]
